'use client';

import { useState } from 'react';
import { useCallStore } from '@/app/store/callStore';
import { Send, Sparkles, Loader2 } from 'lucide-react';

const quickPrompts = [
  'Summarize the conversation',
  'Key action items',
  'Client concerns',
  'Next steps',
];

export default function PromptActions() {
  const [prompt, setPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const { addAIResponse, transcript, notes } = useCallStore();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim()) return;

    setIsGenerating(true);
    
    setTimeout(() => {
      const context = [
        ...transcript.slice(-3).map(t => t.text),
        ...notes.slice(-2).map(n => n.content),
      ];
      
      const mockResponse = `Based on the conversation, here's a structured response to: "${prompt}"\n\n[This is a mock AI response. In production, this would be generated by your AI service.]`;
      
      addAIResponse({
        prompt: prompt.trim(),
        response: mockResponse,
        context: context.filter(Boolean),
      });
      
      setPrompt('');
      setIsGenerating(false);
    }, 1500);
  };

  const handleQuickPrompt = (quickPrompt: string) => {
    setPrompt(quickPrompt);
  };

  return (
    <div className="bg-white border border-blue-200/50 rounded-lg p-3 sm:p-4 shadow-sm">
      <div className="mb-2 sm:mb-3">
        <div className="flex flex-wrap gap-1.5 sm:gap-2">
          {quickPrompts.map((qp) => (
            <button
              key={qp}
              onClick={() => handleQuickPrompt(qp)}
              className="px-2 sm:px-3 py-1 sm:py-1.5 text-[10px] cursor-pointer sm:text-xs border border-blue-200/50 rounded-md bg-blue-50/50 text-blue-700 hover:bg-blue-100 hover:border-blue-300 transition-all shadow-sm"
            >
              {qp}
            </button>
          ))}
        </div>
      </div>
      
      <form onSubmit={handleSubmit} className="flex flex-col sm:flex-row gap-2 sm:gap-3">
        <div className="flex-1 relative">
          <Sparkles className="absolute left-2.5 sm:left-3 top-2.5 sm:top-3 w-3.5 h-3.5 sm:w-4 sm:h-4 text-blue-500" />
          <input
            type="text"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="Ask AI for insights..."
            className="w-full pl-9 sm:pl-10 pr-2.5 sm:pr-3 py-2 sm:py-2.5 text-sm border border-blue-200/50 rounded-lg bg-blue-50/30 text-zinc-900 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-blue-400 shadow-sm transition-colors"
          />
        </div>
        <button
          type="submit"
          disabled={isGenerating || !prompt.trim()}
          className="px-4 sm:px-5 py-2 sm:py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 cursor-pointer text-white rounded-lg hover:from-blue-700 hover:to-indigo-700 transition-all flex items-center justify-center gap-2 text-sm font-medium shadow-sm hover:shadow disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isGenerating ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <Send className="w-4 h-4" />
          )}
          <span className="sm:inline">Generate</span>
        </button>
      </form>
    </div>
  );
}
